<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIadru0q\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIadru0q/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIadru0q.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIadru0q\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIadru0q\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Iadru0q',
    'container.build_id' => '4c2e93a9',
    'container.build_time' => 1529355735,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIadru0q');
